### Invertible Matrices

In [131]:
Inv1=[[0, 2, 0],[2,2,0],[2,1,2]]
Inv2=[[2, 3, 1],[4,7,5],[0,-2,2]]
Inv2_b=[8,20,0]
Inv3=[[2, 5, 1],[4,1,1],[0,1,-1]]
Inv3_b=[0,2,3]
Inv4=[[1, 2, 3],[6,5,4],[3,3,1]]
Inv5=[[2, 4, -2],[4,9,-3],[-2,-3,7]]

## r < n Matrices for Special Solutions, Ax = 0

In [129]:
sps1 = [[1,2,2,4,6],[1,2,3,6,9],[0,0,1,2,3]]
sps2 = [[2,4,2],[0,4,4],[0,8,8]]
sps3 = [[1,3,0,2],[0,0,1,4],[2,5,1,4]]
sps4 = [[1,2,3,5],[2,4,8,12],[3,6,7,13]]

## r < n Matrices for Complete Solutions, Ax = b

In [130]:
# the _b notation indicates a b vector to use with the matrix A that has the corresponding name
cpsm1 = [[1,2,1,0],[2,4,4,8],[4,8,6,8]]
cpsm1_b = [4,2,10]
cpsm2 = [[2,4,6,4],[2,5,7,6],[2,3,5,2]]
cpsm2_b = [4,3,5]
cpsm3 = [[1,3,3],[2,6,9],[-1,-3,3]]
cpsm3_b = [1,5,5]
cpsm4 = [[1,3,1,3],[2,6,4,8],[0,0,2,4]]
cpsm4_b = [1,3,1]

## Square Invertible Matrix
#### Use the Determinant to Test Your Self at G-J and LU Decomp

In [133]:
# Alternately, generate your own invertible matrix
import numpy as np

def generate_invertible_matrix():
    while True:
        matrix = np.random.randint(-5, 5, size=(3, 3))
        # Only return it if it's invertible.
        if np.linalg.det(matrix)!= 0:
            return matrix

invmatrix = generate_invertible_matrix()

# It's no use printing the inverse, bc it will be delivered in unfriendly decimals.
# You just have to test it with G-J AI form yourself.

print(Inv5)
determinant = np.linalg.det(Inv5)
inverse = np.linalg.inv(Inv5)

print('determinant',determinant)
print('inverse',inverse)

[[2, 4, -2], [4, 9, -3], [-2, -3, 7]]
determinant 7.999999999999998
inverse [[6.750000 -2.750000 0.750000]
 [-2.750000 1.250000 -0.250000]
 [0.750000 -0.250000 0.250000]]


##  Square Singular Matrix

In [74]:
import numpy as np

def generate_invertible_matrix():
    while True:
        matrix = np.random.randint(-10, 11, size=(3, 3))
        # Only return it if it's not invertible.
        if np.linalg.det(matrix)== 0:
            return matrix

matrix = generate_invertible_matrix()
print(invmatrix)


[[ -2  -4   0]
 [  7 -10   7]
 [ -6   0  -5]]


## Rectangular

In [24]:
import numpy as np


def generate_invertible_matrix(m,n):
    matrix = np.random.randint(-10, 11, size=(m, n))
    return matrix

matrix = generate_invertible_matrix(3,5)
print(matrix)


[[ -5  -6   9  -6  -1]
 [ -1   0   3  -3  -6]
 [-10  -8   9  -6  -8]]


## Skew-Symmetric

In [25]:
import numpy as np

def generate_skew_symmetric_matrix():
    # Generate a 3x3 skew-symmetric matrix
    a = np.random.randint(-10, 11)
    b = np.random.randint(-10, 11)
    c = np.random.randint(-10, 11)
    
    matrix = np.array([[0, -c, b],
                       [c, 0, -a],
                       [-b, a, 0]])
    return matrix

matrix = generate_skew_symmetric_matrix()
print(matrix)

[[  0   3 -10]
 [ -3   0   0]
 [ 10   0   0]]


## Row * Column

In [50]:
import numpy as np

def generate_matrix(m,n):
    matrix = np.random.randint(-10, 11, size=(m,n))
    
    return matrix

row_matrix = generate_matrix(3,1)
col_matrix = generate_matrix(1,3)
matrix = np.dot(row_matrix,col_matrix)

print(col_matrix)
print(row_matrix)
print(matrix)

[[-10  -6  -7]]
[[-10]
 [  9]
 [ -1]]
[[100  60  70]
 [-90 -54 -63]
 [ 10   6   7]]


## 3x3 Invertible with LDU, Determinant
#### Practice LU = A, Determinant: For Any Invertible Matrix, Det = Product of U Diagonals

In [60]:
import numpy as np

def generate_invertible_matrix():
    while True:
        matrix = np.random.randint(-10, 11, size=(3, 3))
        # Only return it if it's invertible.
        if np.linalg.det(matrix)!= 0:
            return matrix

def lu_decomposition(A):
    n = len(A)
    L = np.zeros((n, n))
    U = np.zeros((n, n))

    for i in range(n):
        L[i][i] = 1
        for k in range(i, n):
            s = sum(L[i][j] * U[j][k] for j in range(i))
            U[i][k] = A[i][k] - s
        for k in range(i + 1, n):
            s = sum(L[k][j] * U[j][i] for j in range(i))
            L[k][i] = (A[k][i] - s) / U[i][i]

    return L, U

# Example usage:

A = generate_invertible_matrix()

print('A',A)
L, U = lu_decomposition(A)
print("L:")
print(L)
print("U:")
print(U)

A2 = np.dot(L,U)

print('A2',A2)

determinant = np.linalg.det(A2)

print('determinant',determinant)

A [[ -1  -1   3]
 [  8   7   5]
 [  6 -10  -2]]
L:
[[ 1.  0.  0.]
 [-8.  1.  0.]
 [-6. 16.  1.]]
U:
[[  -1.   -1.    3.]
 [   0.   -1.   29.]
 [   0.    0. -448.]]
A2 [[ -1.  -1.   3.]
 [  8.   7.   5.]
 [  6. -10.  -2.]]
determinant -447.9999999999995


## Eigenvectors, Eigenvalues

In [62]:
import numpy as np

# Define the 3x3 matrix
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculate the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Print the eigenvalues and eigenvectors
print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)


Eigenvalues:
[ 1.61168440e+01 -1.11684397e+00 -4.29954797e-16]
Eigenvectors:
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


## Left Nullspace

In [72]:
import numpy as np
from scipy.linalg import null_space

np.set_printoptions(suppress=True,
   formatter={'float_kind':'{:f}'.format})

def left_null_space(A):
    """
    Computes the left null space of a matrix A.

    Args:
      A: A numpy array representing the matrix.

    Returns:
      A numpy array whose columns form an orthonormal basis for the left null space of A.
      Returns an empty array if the left null space is trivial.
    """
    return null_space(A.T)

# Example usage:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
left_null_basis = left_null_space(A)
print("Left null space basis:")
print(left_null_basis)

# Verify that the vectors returned are in the left null space:
for i in range(left_null_basis.shape[1]):
    x = left_null_basis[:, i]
    print("A.T @ x:", np.dot(A.T, x))

Left null space basis:
[[0.408248]
 [-0.816497]
 [0.408248]]
A.T @ x: [-0.000000 -0.000000 -0.000000]
